package com.netcentric.brainery.yamldialog.common.validation.rule.panel;

import com.netcentric.brainery.yamldialog.api.model.yaml.Panel;
import com.netcentric.brainery.yamldialog.api.validation.ItemValidationRule;
import com.netcentric.brainery.yamldialog.api.validation.ValidationResult;
import com.netcentric.brainery.yamldialog.api.validation.model.Severity;

public class PanelValidationRule implements ItemValidationRule<Panel> {

	@Override
	public ValidationResult pass(Panel item) {
		if(item.title.startsWith("rndtitle")) {
			return ValidationResult.invalid(Severity.WARNING, "add title property, otherwise autogenerated random title will be displayed", item);
		}
		return ValidationResult.valid();
	}

}
