package com.netcentric.brainery.yamldialog.api.model;

public enum AnnotationType {
	CALENDAR, CHECKBOX, DIALOG_SIMPLE, DIALOG_MULTI, IMAGE, MULTIFIELD, NUMBERFIELD, OPTION, PANEL, PATHFIELD, SELECT, TAGFIELD, 
	TEXTAREA, TEXTFIELD, DROPTARGET, DROPTARGETS, INPLACEEDITING, EDITCONFIG, IMPORT, RADIOGROUP, RADIO, TEXT, PASSWORD, SWITCH, 
	COLORFIELD, FIELDSET, TAGFIELD_LIST, FRAGMENT;

	public String toString() {
		return name().toLowerCase();
	}
}
